In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
A = np.float64(np.array( [[4, 2/3, -(4/3), 4/3], 
                          [2/3, 4, 0, 0],
                          [-(4/3), 0, 6, 2],
                          [4/3, 0, 2, 6]]))
A

array([[ 4.        ,  0.66666667, -1.33333333,  1.33333333],
       [ 0.66666667,  4.        ,  0.        ,  0.        ],
       [-1.33333333,  0.        ,  6.        ,  2.        ],
       [ 1.33333333,  0.        ,  2.        ,  6.        ]])

In [3]:
def get_eigs_QR(A, maxiter = 2, print_everything=False):
    """
    Eigenvalue and eigenvectors computation using the QR factorization
    algorithm uses np.linalg.qr() for the QR factorization
    
    Parameters:
                * A symmetric nxn matrix
                * maxiter = 2 (default) number of iterations
                * print_everything = False (default) print details for each iteration
    Returns:
            * A : nxn matrix whose diagonal contains the approximation of eigenvalues of matrix A
            * P : nxn matrix whose each column is an eigenvector of matrix A
    """
    A_1 = A.copy()
    P = np.identity(A.shape[0])
    Q , R = LA.qr(A_1)
    if print_everything:
        print("Starting with")
        print("A[1] = ")
        print(A_1)
        print("P[0] = ")
        print(P)
        print("")
    for s in range(maxiter):
        A_new = np.matmul(R,Q)
        P = np.matmul(P,Q)
        Q, R = LA.qr(A_new)
        if print_everything:
            print("Iteration: ", s+1)
            print("A[{}]".format(s+2))
            print(A_new)
            print("P[{}]".format(s+1))
            print(P)
            print("eigenvalue approximation:")
            print(np.sort(A_new.diagonal(0)))
            print("")
    return A_new, P


In [4]:
# Approximation of eigenvalues for matrix A
# using our algorithm for 2 iterations
A_eigvals, P_eigvecs = get_eigs_QR(A, print_everything=True)

Starting with
A[1] = 
[[ 4.          0.66666667 -1.33333333  1.33333333]
 [ 0.66666667  4.          0.          0.        ]
 [-1.33333333  0.          6.          2.        ]
 [ 1.33333333  0.          2.          6.        ]]
P[0] = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Iteration:  1
A[2]
[[ 5.6         0.27692308 -0.38193764 -1.10337539]
 [ 0.27692308  3.9147929   0.11751927  0.33950012]
 [-0.38193764  0.11751927  7.40990987 -1.70470481]
 [-1.10337539  0.33950012 -1.70470481  3.07529723]]
P[1]
[[-0.89442719  0.10320314 -0.14233975 -0.41120373]
 [-0.1490712  -0.98616331  0.02372329  0.06853395]
 [ 0.2981424  -0.09173612 -0.87578487 -0.36837001]
 [-0.2981424   0.09173612 -0.46062725  0.8309742 ]]
eigenvalue approximation:
[3.07529723 3.9147929  5.6        7.40990987]

Iteration:  2
A[3]
[[ 5.95121951  0.05412629 -0.0401139   0.43382443]
 [ 0.05412629  3.97034176  0.02198022 -0.23771202]
 [-0.0401139   0.02198022  7.94980035  0.54289988]
 [ 0.43382443 -0.2377120

In [5]:
# for 5 iterations
A_eigvals, P_eigvecs = get_eigs_QR(A,maxiter = 5 )
np.sort(A_eigvals.diagonal(0))

array([2.00056875, 3.99951186, 5.99993226, 7.99998713])

In [6]:
# Computation of eigenvalues using np.linalg
w,v = LA.eigh(A)
w

array([2., 4., 6., 8.])